language: node_js

node_js:
  - node

before_install:
  - yarn config set ignore-engines true

deploy:
  provider: npm
  email: "paul.heasley@gmail.com"
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
